### ISSUE TITLE
Issue with MW 1.38

### ISSUE THREAD

**Issue by HM100** [AWikia/SkinEvelution#103]
When you load Evelution under the stable 1.38, you'll notice that the connection is reset? Is this conflicting Evelution or something else, as its child, Ivilution does work.

**Comment by HM100** [comment]
You can make this still support 1.36 or not. But should support 1.37 and 1.38 at least

**Comment by HM100** [comment]
I have done something but I have another issue
```
MediaWiki internal error.

Original exception: [72ceeb6a35e4ce0ced329eba] /wiki/index.php?title=%CE%95%CE%B9%CE%B4%CE%B9%CE%BA%CF%8C:%CE%88%CE%BA%CE%B4%CE%BF%CF%83%CE%B7 Error: Cannot use object of type EmptyBagOStuff as array
Backtrace:
from E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\skins\Skin.php(249)
#0 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\vendor\wikimedia\object-factory\src\ObjectFactory.php(247): Skin->__construct()
#1 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\vendor\wikimedia\object-factory\src\ObjectFactory.php(152): Wikimedia\ObjectFactory\ObjectFactory::getObjectFromSpec()
#2 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\skins\SkinFactory.php(139): Wikimedia\ObjectFactory\ObjectFactory->createObject()
#3 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\context\RequestContext.php(522): SkinFactory->makeSkin()
#4 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\context\ContextSource.php(174): RequestContext->getSkin()
#5 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\OutputPage.php(2795): ContextSource->getSkin()
#6 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\MediaWiki.php(924): OutputPage->output()
#7 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\MediaWiki.php(937): MediaWiki::{closure}()
#8 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\MediaWiki.php(564): MediaWiki->main()
#9 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\index.php(53): MediaWiki->run()
#10 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\index.php(46): wfIndexMain()
#11 {main}

Exception caught inside exception handler: [72ceeb6a35e4ce0ced329eba] /wiki/index.php?title=%CE%95%CE%B9%CE%B4%CE%B9%CE%BA%CF%8C:%CE%88%CE%BA%CE%B4%CE%BF%CF%83%CE%B7 Error: Cannot use object of type EmptyBagOStuff as array
Backtrace:
from E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\skins\Skin.php(249)
#0 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\vendor\wikimedia\object-factory\src\ObjectFactory.php(247): Skin->__construct()
#1 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\vendor\wikimedia\object-factory\src\ObjectFactory.php(152): Wikimedia\ObjectFactory\ObjectFactory::getObjectFromSpec()
#2 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\skins\SkinFactory.php(139): Wikimedia\ObjectFactory\ObjectFactory->createObject()
#3 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\context\RequestContext.php(522): SkinFactory->makeSkin()
#4 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\context\ContextSource.php(174): RequestContext->getSkin()
#5 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\OutputPage.php(2795): ContextSource->getSkin()
#6 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\exception\MWExceptionRenderer.php(157): OutputPage->output()
#7 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\exception\MWExceptionRenderer.php(76): MWExceptionRenderer::reportHTML()
#8 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\exception\MWExceptionHandler.php(107): MWExceptionRenderer::output()
#9 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\exception\MWExceptionHandler.php(202): MWExceptionHandler::report()
#10 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\includes\MediaWiki.php(586): MWExceptionHandler::handleException()
#11 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\index.php(53): MediaWiki->run()
#12 E:\Bitnami\mediawiki-1.35.1-3\apps\mediawiki\htdocs\index.php(46): wfIndexMain()
#13 {main}
```

**Comment by HM100** [comment]
Also, MW does not give which file has the error so as to quickly fix that

**Comment by HM100** [comment]
I have fixed that issue, I have made changes to no longer support MW 1.37 and still encountering the Connection Reset issue.

**Comment by HM100** [comment]
Evelution now no longer supports MW1.36 as it reached EOL

**Comment by HM100** [comment]
Issue appears to be on the following Files:
- Taskmar.mustasche in the templates folder
- Jave_Base.mustache in the templates folder
- Java_Theming.mustasche in the templates folder
- Java_Header.mustache in the templates folder
- SkinEvelution.php in the root folder
Once you send up a PR, only edit those files, not anything else and only to fix up the 1.38 bugs

**Comment by HM100** [comment]
Tried on my newly created MW instance, still the same issue

**Comment by HM100** [comment]
And this can't be repro under 1.37

**Comment by HM100** [comment]
And this cannot be repro under some other wikis on 1.38. It must be local storage the issue
